services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Admin@123
      - DB_NAME=orderservice
      - DB_PORT=3306
    networks:
      - kong-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: orderdb
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=orderservice
    ports:
      - "3309:3306"
    networks:
      - kong-network
    volumes:
      - order_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  order_data:

networks:
  kong-network:
    external: true